---
- name: Stop netfilter
  ansible.builtin.service:
    name: netfilter-persistent
    state: stopped

- name: Set mulriport if need
  ansible.builtin.set_fact:
    multiport: " -m multiport "
  when: secure_ports|length > 1

- name: Writes the /etc/default/knockd
  ansible.builtin.template:
    src: templates/knockd.j2
    dest: /etc/default/knockd
    mode: "0400"
  notify: Start knockd

- name: Writes the knockd conf
  ansible.builtin.template:
    src: templates/knockd.conf.j2
    dest: /etc/knockd.conf
    mode: "0640"

  notify: Start knockd

- name: Allow loopback interface traffic
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

  become: true

- name: Allow established traffic
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

  become: true

- name: Allow open ports traffic
  ansible.builtin.iptables:
    chain: INPUT
    destination_port: "{{ item }}"
    protocol: tcp
    match: tcp
    jump: ACCEPT
  become: true
  with_items: "{{ open_ports }}"

- name: Drop the rest of traffic
  ansible.builtin.iptables:
    chain: INPUT
    jump: DROP

  become: true

- name: Save rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  args:
    creates: /etc/iptables/rules.v4
- name: Start netfilter
  ansible.builtin.service:
    name: netfilter-persistent
    state: started
