---
- name: Converge
  hosts: all
  gather_facts: false
  # tasks:
  #   - name: Replace this task with one that validates your content
  #     ansible.builtin.debug:
  #       msg: "This is the effective test"

  roles:
    - { role: ansible-port-knocking, port_sequence: [24334,34534,2287], secure_ports: [22], open_ports: [80, 443], command_line_options: "-i ens3" }
